[profile.default]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'oz/=lib/openzeppelin-contracts/contracts/',
    'oz-up/=lib/openzeppelin-contracts-upgradeable/contracts/'
]
optimizer = false

[profile.production]
optimizer = true
via_ir = true
optimizer_runs = 1000000
evm_version = "paris"

[fuzz]
runs = 16384

[profile.ci.fuzz]
runs = 100000