name: Tests
on:
    push:
        branches:
            - develop
            - staging
            - main
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop
            - staging
            - main
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
jobs:
    forge-tests:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "pnpm"
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly
            - name: Build
              run: forge build
              env:
                  FOUNDRY_PROFILE: ci
            - name: Test
              run: forge test
              env:
                  FOUNDRY_PROFILE: ci
